### ISSUE TITLE
More than one DbContext was found.

### ISSUE THREAD

**Issue by pedrosantos-sharkdata** [dotnet/EntityFramework.Docs.pt-br#20]
olá, este erro aparece após utilizar o comando "dotnet ef migrations add InitialCreate".
ele dá start na build, me aparece o succeeded.
porém juntamente com isto o seguinte erro.
"More than one DbContext was found. Specify which one to use. Use the '-Context' parameter for PowerShell commands and the '--context' 
parameter for dotnet commands."

O que poderia ser ?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 7ac57b24-45aa-e679-6ff9-5a25c369c1ff
* Version Independent ID: cc576199-b14c-a135-2291-cc48bf301b4e
* Content: [Introdução – EF Core](https://docs.microsoft.com/pt-br/ef/core/get-started/?tabs=netcore-cli#feedback)
* Content Source: [entity-framework/core/get-started/index.md](https://github.com/dotnet/EntityFramework.Docs.pt-br/blob/live/entity-framework/core/get-started/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **avickers**

**Comment by srvbpigh** [comment]
Hello, @pedrosantos-sharkdata
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
> hello, this error appears after using the command "dotnet ef migrations add InitialCreate".
he starts the build, appears successfuled.
however along with this the following error.
"More than one DbContext was found. Specify which one to use. Use the '-Context' parameter for PowerShell commands and the '--context'
parameter for dotnet commands. "
> 
> What could it be ?

The tutorial works. Your problem is you have More than one DbContext. I suggest you remove one or start over.

O tutorial funciona. Seu problema é que você tem mais de um DbContext. Eu sugiro que você remova um ou comece de novo.

Recommend closing.
