### ISSUE TITLE
Related data and serialization

### ISSUE THREAD

**Issue by Schinwinkwinsky** [dotnet/EntityFramework.Docs.pt-br#21]
'JsonOptions' does not contain a definition to "SerializerSettings" and it was not possible to find any extension method.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: bbd36f35-e257-d0ed-8f28-f539ddcb71ec
* Version Independent ID: 093903d5-f7c7-5a78-c0e5-0e2662dcedef
* Content: [Como carregar dados relacionados – EF Core](https://docs.microsoft.com/pt-br/ef/core/querying/related-data#feedback)
* Content Source: [entity-framework/core/querying/related-data.md](https://github.com/dotnet/EntityFramework.Docs.pt-br/blob/live/entity-framework/core/querying/related-data.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **avickers**

**Comment by srvbpigh** [comment]
Hello, @Schinwinkwinsky
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @Schinwinkwinsky, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/EntityFramework.Docs/issues/2233. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
